package dev.sophi.companion.ui

import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.InternalComposeUiApi
import androidx.compose.ui.LocalSystemTheme
import androidx.compose.ui.Modifier
import androidx.compose.ui.SystemTheme
import androidx.compose.ui.graphics.Color
import dev.sophi.companion.SessionState

// Seeded from the octopus logo (doc/images/logo.png) — hand-authored Material 3 tonal
// roles around that violet, not generated by a theme-builder tool.
private val SophiLightColors = lightColorScheme(
    primary = Color(0xFF6C5CE7),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE4DEFF),
    onPrimaryContainer = Color(0xFF201150),
    secondary = Color(0xFF5D5C77),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE3E0F9),
    onSecondaryContainer = Color(0xFF1A1836),
    tertiary = Color(0xFF8B5000),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDDB3),
    onTertiaryContainer = Color(0xFF2C1600),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFE5E0EC),
    onSurfaceVariant = Color(0xFF48454E),
    outline = Color(0xFF79767F),
    surfaceContainer = Color(0xFFEEE8F4),
    surfaceContainerLow = Color(0xFFF6F0FA),
    surfaceContainerHigh = Color(0xFFE8E2EE),
)

private val SophiDarkColors = darkColorScheme(
    primary = Color(0xFFC6BEFF),
    onPrimary = Color(0xFF33256F),
    primaryContainer = Color(0xFF4A3D89),
    onPrimaryContainer = Color(0xFFE4DEFF),
    secondary = Color(0xFFC6C4E4),
    onSecondary = Color(0xFF2F2E45),
    secondaryContainer = Color(0xFF46445C),
    onSecondaryContainer = Color(0xFFE3E0F9),
    tertiary = Color(0xFFFFB865),
    onTertiary = Color(0xFF472A00),
    tertiaryContainer = Color(0xFF653F00),
    onTertiaryContainer = Color(0xFFFFDDB3),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF131318),
    onBackground = Color(0xFFE5E1E9),
    surface = Color(0xFF131318),
    onSurface = Color(0xFFE5E1E9),
    surfaceVariant = Color(0xFF48454E),
    onSurfaceVariant = Color(0xFFC9C5D0),
    outline = Color(0xFF928F99),
    surfaceContainer = Color(0xFF1E1D26),
    surfaceContainerLow = Color(0xFF18171F),
    surfaceContainerHigh = Color(0xFF282731),
)

@OptIn(InternalComposeUiApi::class)
@Composable
fun SophiTheme(content: @Composable () -> Unit) {
    // LocalSystemTheme is @InternalComposeUiApi — no stable public alternative exists yet for
    // reading OS light/dark on Compose Desktop. Safe here: this app pins one exact Compose
    // version (1.9.0) rather than spanning compose-ui modules of different versions, which is
    // what the annotation warns against.
    val isDark = LocalSystemTheme.current == SystemTheme.Dark
    MaterialTheme(
        colorScheme = if (isDark) SophiDarkColors else SophiLightColors,
    ) {
        // Without this, only widgets that use Surface internally (ListItem, TextField, ...)
        // pick up the theme — plain Column/Box content never gets a background painted at all,
        // leaving the window's raw unstyled canvas showing through everywhere else.
        Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
            content()
        }
    }
}

// Traffic-light status colors, deliberately independent of the brand (violet) palette above —
// "running" reading as green and "needs confirmation" reading as orange is a universal enough
// convention that borrowing the accent color for it (as the theme originally did) reads wrong.
val SessionActiveColor = Color(0xFF2FA84F)
val SessionAttentionColor = Color(0xFFF29B11)

/** Semantic status color — same mapping used by the sidebar dot, the Chat panel header, and the confirmation card. */
fun statusColor(state: SessionState, colors: ColorScheme): Color = when (state) {
    SessionState.Idle -> colors.onSurfaceVariant
    SessionState.Running -> SessionActiveColor
    is SessionState.NeedsConfirmation -> SessionAttentionColor
    is SessionState.Error -> colors.error
}
